#!/usr/bin/env php
<?php

use Illuminate\Console\Application;
use Illuminate\Events\Dispatcher;
use Ypho\Hashing\Commands\Benchmark\Argon;
use Ypho\Hashing\Commands\Benchmark\Bcrypt;
use Ypho\Hashing\Commands\Benchmark\Md5;
use Ypho\Hashing\Commands\Benchmark\Sha1;
use Ypho\Hashing\Commands\Benchmark\Sha256;
use Ypho\Hashing\Commands\BruteForce\StrongAlgorithms;
use Ypho\Hashing\Commands\BruteForce\WeakAlgorithms;
use Ypho\Hashing\Commands\Generate;
use Ypho\Hashing\Container;

require __DIR__.'/vendor/autoload.php';

$container = new Container();
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'v1');
$artisan->setName('Hashing Console');

// General commands
$artisan->resolve(Generate::class);

// Brute force commands
$artisan->resolve(WeakAlgorithms::class);
$artisan->resolve(StrongAlgorithms::class);

// Benchmark commands
$artisan->resolve(Md5::class);
$artisan->resolve(Sha1::class);
$artisan->resolve(Sha256::class);
$artisan->resolve(Bcrypt::class);
$artisan->resolve(Argon::class);

$artisan->run();