#!/usr/bin/env php
<?php

use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Ypho\Hashing\Commands\BruteForce\Bcrypt;
use Ypho\Hashing\Commands\BruteForce\WeakAlgorithms;

require __DIR__.'/vendor/autoload.php';

$container = new Container();
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'v1');
$artisan->setName('Hashing Console');

// Bind commands
$artisan->resolve(WeakAlgorithms::class);
$artisan->resolve(Bcrypt::class);

$artisan->resolve(\Ypho\Hashing\Commands\Benchmark\Md5::class);
$artisan->resolve(\Ypho\Hashing\Commands\Benchmark\Sha1::class);
$artisan->resolve(\Ypho\Hashing\Commands\Benchmark\Sha256::class);
$artisan->resolve(\Ypho\Hashing\Commands\Benchmark\Bcrypt::class);
$artisan->resolve(\Ypho\Hashing\Commands\Benchmark\Argon::class);

$artisan->run();